name: Atualizar Manchetes

on:
  schedule:
    - cron: '0 */6 * * *'  # Executa a cada 6 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install feedparser

      - name: Executar script de notícias
        run: python noticias.py

      - name: Commit e push das manchetes atualizadas
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manchetes.txt feed.xml
          git commit -m "Atualização automática das manchetes"
          git push origin main
