name: Atualizar Notícias Internacionais

on:
  schedule:
    - cron: '0 8 * * *'  # Executa todo dia às 08h UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  coletar_noticias:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install feedparser newspaper3k googletrans==4.0.0-rc1
      
      - name: Rodar script de notícias
        run: python noticias.py

      - name: Commitar e enviar atualizações
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manchetes.txt
          git commit -m "🚀 Atualização automática das notícias"
          git push
